name: Example Workflow

on:
  push:
    branches:
      - ESCROW_KC2_I166

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print commit message
      run: echo "Commit Message: ${{ github.event.head_commit.message }}"

    - name: Count characters in commit message
      run: echo "Character Count: ${#GITHUB_EVENT_PATH}"

