name: Enforce Commit Message Length

on:
  pull_request:
    branches:
      - main

jobs:
  enforce-commit-message-length:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set and Validate Commit Message Length
      run: |
        commit_message=$(git log --format=%B -n 1 ${{ github.event.before }}..${{ github.sha }})
        commit_length=$(echo $commit_message | wc -c)

        if [ $commit_length -gt 15 ]; then
          echo "Error: Commit message length exceeds 15 characters."
          echo "Please provide a commit message with 15 characters or fewer."
          exit 1
        fi
