name: Example Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check commit message length
      run: |
        commit_message="${{ github.event.pull_request.title }}"
        if [ ${#commit_message} -gt 15 ]; then
          echo "Commit message is too long. Maximum allowed length is 15 characters."
          exit 1  # This will cause the step (and subsequently the workflow) to fail
        fi

