name: Commit Message Length Check

on:
  pull_request:
    branches:
      - ESCROW_KC2_I166

jobs:
  commit-message-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Check Commit Message Length
      run: |
        COMMIT_MESSAGE=$(git log --pretty=%B $GITHUB_SHA^..$GITHUB_SHA)
        COMMIT_LENGTH=${#COMMIT_MESSAGE}

        if [ $COMMIT_LENGTH -ge 15 ]; then
          echo "Error: Commit message length exceeds 15 characters."
          exit 1
        fi
