name: Check Commit Message Length

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  check-commit-message:
    runs-on: ubuntu-latest

    steps:
      - name: Check Commit Message Length
        uses: actions/checkout@v2

      - name: Get Commit Message
        id: commit_message
        run: echo "::set-output name=message::$(git log --format=%B -n 1 ${{ github.sha }})"

      - name: Check Message Length
        run: |
          message_length=$(echo "${{ steps.commit_message.outputs.message }}" | wc -m)
          if [ $message_length -le 15 ]; then
            echo "Commit message must be more than 15 characters."
            exit 1
          fi
