name: Pull Request Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print commit message
      run: echo "Commit Message: ${{ github.event.pull_request.title }}"

