name: Check Commit Message Length

on:
  push:
    branches:
      - ESCROW_KC2_I166

jobs:
  check_commit_message_length:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Check Commit Message Length
      run: |
        commit_message=$(git log --format=%B -n 1 $GITHUB_SHA)
        if [ ${#commit_message} -gt 15 ]; then
          echo "Error: Commit message must not exceed 15 characters."
          exit 1
        else
          echo "Commit message length check passed."
        fi

    - name: Merge Code
      if: success()
      run: echo "Code merged successfully!"
